In [5]:
import duckdb

query = ''' 
    select
    puzzle_number,
    answer,
    count(*) as times_used
    from raw_wordle_words
    group by puzzle_number ,answer
    having count(*) > 1'''
with duckdb.connect("./data/wordle.db") as con:
    display(con.query(query).df())

Empty DataFrame
Columns: [puzzle_number, answer, times_used]
Index: []

In [7]:
query = ''' 
    show all tables'''
with duckdb.connect("./data/wordle.db") as con:
    display(con.query(query).df())

,database,schema,name,column_names,column_types,temporary
0,wordle,main,all_5_letter_words,[word],[VARCHAR],False
1,wordle,main,raw_wordle_words,"[puzzle_number, answer, date, day_name, diffic...","[INTEGER, VARCHAR, DATE, VARCHAR, FLOAT, TIMES...",False
2,wordle,main_marts,mart_answer_history,"[puzzle_number, answer, answer_date, day_name,...","[INTEGER, VARCHAR, DATE, VARCHAR, BIGINT, BIGI...",False
3,wordle,main_marts,mart_letter_frequency,"[letter, total_count, frequency_pct, frequency...","[VARCHAR, BIGINT, DOUBLE, BIGINT]",False
4,wordle,main_marts,mart_position_heatmap,"[position, letter, position_count, position_pct]","[INTEGER, VARCHAR, BIGINT, DOUBLE]",False
5,wordle,main_marts,mart_top_predictions,"[rank, word, letter_1, letter_2, letter_3, let...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, V...",False
6,wordle,main_marts,mart_word_scores,"[word, letter_1, letter_2, letter_3, letter_4,...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
7,wordle,main_staging,stg_wordle_words,"[puzzle_number, answer, letter_1, letter_2, le...","[INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False